--Loli Yuzora
function c56540003.initial_effect(c)
 local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_BATTLE_DESTROY_REDIRECT)
	e1:SetValue(LOCATION_DECKBOT)
	c:RegisterEffect(e1)
  local e2=Effect.CreateEffect(c)
	  e2:SetType(EFFECT_TYPE_FIELD)
	  e2:SetCode(EFFECT_TRAP_ACT_IN_SET_TURN)
	  e2:SetProperty(EFFECT_FLAG_SET_AVAILABLE)
	  e2:SetRange(LOCATION_MZONE)
	  e2:SetTargetRange(LOCATION_SZONE,0)
	  e2:SetCountLimit(1)
	  c:RegisterEffect(e2)
	--spsummon
	 local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD)
	e3:SetCode(EFFECT_TRAP_ACT_IN_HAND)
	e3:SetProperty(EFFECT_FLAG_SET_AVAILABLE)
	e3:SetRange(LOCATION_MZONE)
	e3:SetTargetRange(LOCATION_HAND,0)
	e3:SetCountLimit(1)
	c:RegisterEffect(e3)	
end
